config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  
  devise_scope :user do 
    unauthenticated do 
      root 'devise/sessions#new', as: :unauthenticated_root
    end

    authenticated :user do 
      root 'static_pages#home', as: :authenticated_root
    end
  end

  resources :posts
  resources :activities
  
  match 'user/:id', :to => "user#show", :as => :user, :via => :get
end

app/models/post.rb
class Post < ActiveRecord::Base
  before_save :encrypt_body 
  attr_accessor :crypt
  belongs_to :user
  include PublicActivity::Common

  validates_presence_of :user
  validates :private, inclusion: [true, false]

  # scope :public_posts, -> { where('post_type == ?', "public") }
  # scope :private_posts, -> { where('post_type == ?', "private") }

  def encrypt_body
    crypt = ActiveSupport::MessageEncryptor.new(Rails.application.secrets.secret_key_base)
    encrypted_data = crypt.encrypt_and_sign(self.body)
    self.body = encrypted_data
  end

  def decrypt
    crypt = ActiveSupport::MessageEncryptor.new(Rails.application.secrets.secret_key_base)
    crypt.decrypt_and_verify(self.body)
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_uniqueness_of :username
  validates_presence_of :username

  has_many :posts

  def public_posts
    self.posts.where(private: false)
  end

  def private_posts
    self.posts.where(private: true)
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  def index
    @activities = PublicActivity::Activity.order("created_at desc")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :username, :password, :password_confirmation) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:email, :username, :password, :password_confirmation) }
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        @post.create_activity :create, owner: current_user if !@post.private?
        flash[:success] = "Post created!"
        format.html { redirect_to :back }
        format.js
      else
        render 'new'
      end
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(post_params)
      flash[:success] = "Post updated"
    else
      render :edit
    end
  end

  def edit 
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.create_activity :destroy, owner: current_user if !@post.private
    @post.destroy
    flash[:success] = "Post deleted" 
    redirect_to :authenticated_root
  end

  private

    def post_params
      params.require(:post).permit(:body, :private, :crypt)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    @posts = current_user.posts.all.paginate(page: params[:posts_page], per_page: 15).order("updated_at desc")
    @activities = PublicActivity::Activity.paginate(page: params[:activities_page], per_page: 10).order("created_at desc")
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/activities/index.html.erb
<% @activities.each do |activity| %>
  <div id="activity">
    <%= link_to activity.owner.username, activity.owner if activity.owner %>
    <%= render_activity activity %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

<%= yield %>
  <%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post, id: "new-post", remote: true do |f| %>
  
  <p>
  <%= f.label :body %>
  <%= f.text_area :body %>
  </p>

  <p>
    <%= f.label :private, 'Public', value: false %>
  <%= f.radio_button :private, false, checked: true %>
  </p>

  <p>
    <%= f.label :private, 'Private', value: true %>
  <%= f.radio_button :private, true %>
  </p>

  <%= f.submit 'Create post' %>

<% end %>

app/views/posts/_post.html.erb
<%= link_to post_path(post) do %>
  <div id="post-body"><%= truncate(post.decrypt) %></div>
<% end %>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/create.js.erb
$('form').remove();
$("<%= j render @post %>").prependTo("#posts-feed");

app/views/posts/destroy.html.erb
<h1>Posts#destroy</h1>
<p>Find me in app/views/posts/destroy.html.erb</p>

app/views/posts/edit.html.erb
<%= provide(tite: 'Edit Post') %>
  <h1>Edit post</h1>

<%= form_for @post do |f| %>
  
  <p>
  <%= f.label :body %>
  <%= f.text_area :body, value: @post.decrypt %>
  </p>

  <p>
    <%= f.label :private, 'Public', value: false %>
  <%= f.radio_button :private, false, checked: true %>
  </p>

  <p>
    <%= f.label :private, 'Private', value: true %>
  <%= f.radio_button :private, true %>
  </p>

  <%= f.submit 'Save' %>

<% end %>

app/views/posts/index.html.erb
<div id="container">
  <div id="left-div">
    <div id="table-header">
      <div id="entries">
        <strong>Entries</strong>
      </div>
      <div id="new-entry"> 
        <%= link_to 'New Entry', new_post_path, class:"unstyled-link" %>
      </div>
    </div>
      <div id="posts-feed"> 
      </div>

  </div>
  <div id="right-div">

  </div>
</div>

<p><%# link_to 'My Posts', user_path(current_user) %></p>

<table>
  <tr>
    <th>Post</th>
    <th>Author</th>
    <th colspan="2"></th>
  </tr>

  <%# @posts.each do |post| %>
    <tr>
      <%# if !post.private? %>
      <td><%# link_to truncate(post.decrypt), post_path(post) %></td>
      <td><%# link_to post.user.username, user_path(post.user) %></td>
      <%# end %>
  <%# end %>
  </tr>
</table> -->

<!-- <p><%# link_to 'Sign out', destroy_user_session_path, method: :delete %></p> -->

app/views/posts/new.html.erb
<%= provide(tite: 'New Post') %>
  <h1>Create post</h1>

<%= render 'form' %>

app/views/posts/new.js.erb
$('form').remove();
$('#table-header').after('<%= j render("form") unless @form %>')

app/views/posts/show.html.erb
<%= @post.decrypt %>

<% if current_user == @post.user  %>
  <%= link_to 'Edit Post', edit_post_path %>
  <%= link_to 'Delete Post', post_path(@post), method: :delete %>
<% end %>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>

app/views/public_activity/post/_create.html.erb
created a post 
<% if activity.trackable %>
  <%= link_to truncate(activity.trackable.decrypt), activity.trackable %>
  <div id="time-ago">
    <%= time_ago_in_words(activity.trackable.updated_at) %> ago
  </div>
<% else %>
  which has since been removed
<% end %>

app/views/public_activity/post/_destroy.html.erb
removed a post

app/views/static_pages/home.html.erb
<p><%= link_to 'Sign out', destroy_user_session_path, method: :delete %></p>

<div id="container">
  <div id="left-div">
    <div id="table-header">
      <div id="entries">
        <strong>Entries</strong>
      </div>
        <%= link_to new_post_path, remote: true do %>
          <div id="new-entry">New Entry</div>
        <% end %>
    </div>
    <div id="posts-feed">
      <%= render @posts %>
      <%= will_paginate @posts, param_name: 'posts_page' %>
    </div>
  </div>
  <div id="right-div">
    <% @activities.each do |activity| %>
      <div id="activity-feed-body">
        <% case activity.key %>
        <% when  "post.create" %>
          <i class="fi-pencil"></i>
        <% when "post.destroy" %>
          <i class="fi-trash"></i>
        <% when "post.edit" %>
          <i class="fi-clipboard"></i>
        <% else %>
          <i class="fi-power"></i>
        <% end %>
        <div id="feed-message">
          <%= link_to activity.owner.username, activity.owner if activity.owner %>
          <%= render_activity activity %>
        </div>
    </div>
    <% end %>
    <%= will_paginate @activities, param_name: 'activities_page' %>
  </div>
</div>

app/views/user/show.html.erb
<%= provide(:title, "#{@user.username}'s posts") %>

<h3>Post</h3>

  
<% if current_user == @user %>
  <% @user.posts.each do |post| %>
    <p>
      <%= link_to truncate(post.decrypt), post_path(post) %>
      <%= link_to 'Edit Post', edit_post_path(post) %>
      <%= link_to 'Delete Post', post_path(post), method: :delete %>
    </p>
  <% end %>
<% else %>
  <% @user.public_posts.each do |post| %>
    <p><%= link_to truncate(post.decrypt), post_path(post) %></p>
  <% end %>
<% end %>